#!/usr/bin/env python
"""Build the Re:creon Player's Manual.

The manual's prose lives in ``chapters/`` as one Markdown file per chapter.
The appendix of reference tables is *generated* from the port's own game
tables (``recreon.datacnst``, ``recreon.attack``) so the numbers the player
reads can never silently disagree with the numbers the game uses. Then pandoc
is invoked twice: once through ``template.typ`` (typst) for the PDF, once
standalone for the HTML edition.

Usage (from the repository root)::

    uv run python docs/manual/build.py              # tables + PDF + HTML
    uv run python docs/manual/build.py --check      # verify the appendix only
    uv run python docs/manual/build.py --tables     # regenerate the appendix

``--check`` is what ``tests/test_manual.py`` runs; it needs no pandoc.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
CHAPTERS_DIR = HERE / "chapters"
APPENDIX_PATH = HERE / "generated" / "appendix-reference.md"
PDF_PATH = HERE / "recreon-manual.pdf"
HTML_PATH = HERE / "recreon-manual.html"

sys.path.insert(0, str(REPO / "src"))

from recreon import attack, datacnst, types  # noqa: E402
from recreon.designcom import ClassN  # noqa: E402
from recreon.types import (  # noqa: E402
    CARGO_TYPES,
    CONSTR_TYPES,
    DEFNS_TYPES,
    RAWM_TYPES,
    SHIP_TYPES,
    FleetTypes,
    IndusTypes,
    TechLevel,
    TechnologyTypes,
    WorldClass,
    WorldTypes,
)

T = TechnologyTypes
TL = TechLevel

MARKER = (
    "<!-- Generated by docs/manual/build.py from the ported game tables.\n"
    "     Do not edit by hand: run `uv run python docs/manual/build.py --tables`\n"
    "     from the repository root and commit the result. -->"
)


# --- markdown rendering ------------------------------------------------------


#: Short column heads for the wide matrices, keyed by the enum name so the
#: appendix tables stay readable in portrait. The legend is rendered once.
SHORT = {
    "men": "men",
    "nnj": "nnj",
    "amb": "amb",
    "che": "che",
    "met": "met",
    "sup": "sup",
    "tri": "tri",
    "fgt": "fgt",
    "hkr": "hkr",
    "jmp": "jmp",
    "jtn": "jtn",
    "pen": "pen",
    "ssp": "ssp",
    "trn": "trn",
    "BioInd": "Bio",
    "CheInd": "Che",
    "MinInd": "Min",
    "SYGInd": "SYG",
    "SYJInd": "SYJ",
    "SYSInd": "SYS",
    "SYTInd": "SYT",
    "SupInd": "Sup",
    "TriInd": "Tri",
}


def _short_head(x: object) -> str:
    return SHORT.get(x.name, x.name)  # type: ignore[union-attr]


def _md_table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |"]
    lines.append("|" + "|".join([" --- "] * len(header)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _md_wide_table(header: list[str], rows: list[list[str]], label_w: int = 16) -> str:
    """A grid table giving the label column real width.

    Pandoc preserves the relative column widths of a grid table, which the
    pipe form does not let us express -- and the 14-column combat matrices
    render unreadably if the label column shares the page with fourteen
    equal numeric columns. Every column's border must span its widest
    cell or pandoc will not parse the table at all.
    """
    widths = [
        max(label_w, *(len(cells[0]) for cells in [header, *rows])),
    ] + [
        max(4, *(len(cells[i]) for cells in [header, *rows])) for i in range(1, len(header))
    ]

    def border(ch: str) -> str:
        return "+" + "+".join(ch * (w + 2) for w in widths) + "+"

    def body(cells: list[str]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths, strict=True)) + " |"

    assert all(len(c) <= w for c, w in zip(header, widths, strict=True)), header
    parts = [border("-"), body(header), border("=")]
    for r in rows:
        parts.append(body(r))
        parts.append(border("-"))
    return "\n".join(parts)


def _short_name(t: TechnologyTypes) -> str:
    """Abbreviated column heads for the wide combat matrices."""
    fixed = {
        T.NoRes: "None",
        T.def_: "Def",
    }
    return fixed.get(t, t.name.capitalize())


def _min_level() -> dict[TechnologyTypes, TechLevel]:
    """The level at which each technology is first available."""
    out: dict[TechnologyTypes, TechLevel] = {}
    for level in TechLevel:
        for thing in datacnst.TechDev[level]:
            out.setdefault(thing, level)
    return out


def _ordered(things) -> list[TechnologyTypes]:
    """Stable order by the enum's own ordinals."""
    return sorted(things, key=int)


def _level_row(level: TL) -> str:
    return datacnst.TechN[level]


def _things(levels: dict[T, TL], t: T) -> str:
    return _level_row(levels[t])


# --- appendix sections ---------------------------------------------------------


def appendix() -> str:
    parts: list[str] = [
        "# Reference Tables",
        "",
        MARKER,
        "",
        "Every table in this appendix is taken directly from the game's own",
        "data -- the same constants the simulation uses, transcribed from",
        "*DATACNST.PAS* and *ATTACK.PAS*. They are reproduced here so that a",
        "number you read in the manual and a number the game computes are",
        "never two different numbers.",
        "",
        "Units follow the original's conventions:",
        "",
        "- **Population** is counted in units of 100 million.",
        "- **Fuel figures** for ships are scaled: consumption is recorded in",
        "  thousandths of a unit per sector per ship, capacity in hundredths",
        "  of a unit per ship.",
        "- **Raw-material costs** are quantities (megatons, except ambrosia and",
        "  trillum in kilotons) needed to build **100 units** of the thing.",
        "- **Percentages of population in the military** are stored in",
        "  hundredths of one percent.",
        "- A dash means the game has no entry for that cell; a zero is a real",
        "  zero.",
        "",
    ]
    parts += _tech_levels()
    parts += _industries_and_output()
    parts += _ships()
    parts += _cargo_and_defenses()
    parts += _structures()
    parts += _raw_material_costs()
    parts += _combat()
    parts += _world_classes()
    parts += _world_types()
    parts += _fleets_and_limits()
    return "\n".join(parts).rstrip() + "\n"


def _tech_levels() -> list[str]:
    levels = _min_level()
    rows = []
    for level in TechLevel:
        unlocked = ", ".join(
            datacnst.TechnologyName[t]
            for t in _ordered(levels)
            if levels[t] == level
        )
        rows.append(
            [
                str(int(level)),
                _level_row(level),
                str(datacnst.BasePop[level]),
                str(datacnst.TechAdj[level]),
                str(datacnst.TechAdj2[level]),
                str(datacnst.MinSupInd[level]),
                str(datacnst.MilitPer[level]),
                str(attack.GDMLaunch[level]),
                unlocked or "—",
            ]
        )
    return [
        "## Technology Levels",
        "",
        "There are eleven technology levels. **Base population** is the",
        "average population a world of that technology supports at 50%",
        "efficiency, in units of 100 million. **TIP adj** and **prod adj** are",
        "the percent multipliers the level applies to a world's industrial",
        "potential and production; **min supply ind** is the percent of",
        "industry a world needs in food factories to be self-sufficient;",
        "**military pct** is the percent of population in the military at",
        "military index 50 (hundredths of a percent). **GDM salvo** is how",
        "many ground-defense missiles a world can put up at once. The",
        "**Unlocks** column lists the things first buildable at that level.",
        "",
        _md_table(
            [
                "Lvl",
                "Level",
                "Base pop",
                "TIP adj",
                "Prod adj",
                "Min sup ind",
                "Military pct",
                "GDM salvo",
                "Unlocks",
            ],
            rows,
        ),
        "",
    ]


def _industries_and_output() -> list[str]:
    rows = [
        [
            datacnst.IndusNames[ind],
            _level_row(datacnst.MinTechLevel[ind]),
            str(datacnst.NewIndRawN[ind]),
        ]
        for ind in IndusTypes
    ]
    cols = list(datacnst.ThgAdj[IndusTypes.SYGInd])
    matrix_rows = [
        [datacnst.IndusNames[ind]] + [str(v or "—") for v in datacnst.ThgAdj[ind].values()]
        for ind in IndusTypes
    ]
    return [
        "## Industries and Output",
        "",
        "Nine kinds of industry, the technology needed to run them, and the",
        "metal cost of building 100 points of each.",
        "",
        _md_table(["Industry", "Min tech", "Metal per 100"], rows),
        "",
        "What each industry produces, in relative points per 100 points of",
        "that industry. Bio-tech labs produce ambrosia; the food factories",
        "produce supplies; the raw-material industries their eponymous",
        "materials; the yards build hulls. Heads: men and nnj are legions,",
        "amb and tri kilotons, che, met and sup megatons; hull abbreviations",
        "are fgt, hkr, jmp, jtn, pen, ssp, trn.",
        "",
        _md_wide_table(["Industry"] + [_short_head(c) for c in cols], matrix_rows),
        "",
    ]


def _ships() -> list[str]:
    levels = _min_level()
    rows = []
    for s in SHIP_TYPES:
        rows.append(
            [
                datacnst.TechnologyName[s],
                _things(levels, s),
                str(datacnst.MPower[s]),
                str(datacnst.WeapEff[s]),
                str(datacnst.ShipValue[s]),
                str(datacnst.ProtecOffered[s]),
                str(datacnst.ProtecNeeded[s]),
                str(datacnst.TrnAdj[s]),
                str(datacnst.FuelCons[s]),
                str(datacnst.FuelCap[s]),
            ]
        )
    return [
        "## Ships",
        "",
        "Combat power is 0..100 on an absolute scale (a starship anchors the",
        "top end at 100). **Weapon eff** is the average effectiveness of the",
        "type's weapons; **value** and **protection** are the AI's bookkeeping",
        "figures -- how many points a ship of the type is worth and how much",
        "protection it offers or needs. **Trns** is cargo capacity relative",
        "to a transport. Fuel figures are scaled as noted above.",
        "",
        _md_table(
            [
                "Ship",
                "Tech",
                "Power",
                "Weap eff",
                "Value",
                "Prot off",
                "Prot need",
                "Trns",
                "Fuel/sector",
                "Fuel cap",
            ],
            rows,
        ),
        "",
    ]


def _cargo_and_defenses() -> list[str]:
    cargo_rows = []
    for c in CARGO_TYPES:
        cargo_rows.append(
            [
                datacnst.TechnologyName[c],
                str(attack.CombatPower[c]) if c in attack.CombatPower else "—",
                str(datacnst.CargoSpace[c]),
                str(datacnst.FuelCons[c]) if c in datacnst.FuelCons else "—",
            ]
        )
    def_rows = []
    levels = _min_level()
    for d in DEFNS_TYPES:
        costs = datacnst.RawM[d]
        def_rows.append(
            [
                datacnst.TechnologyName[d],
                _things(levels, d),
                str(datacnst.MPower[d]),
                str(datacnst.WeapEff[d]),
                str(datacnst.DefAdj[d]),
                str(datacnst.DefBuildRate[d]),
                " / ".join(str(costs[c]) for c in (T.che, T.met, T.tri)),
            ]
        )
    return [
        "## Cargo and Defenses",
        "",
        "Cargo carried in the hold of a transport. **Space per transport**",
        "is how many units of that cargo one standard transport carries;",
        "a jumptransport carries a fifth of it. **Power** is on the",
        "surrender scale.",
        "",
        _md_table(
            ["Cargo", "Power", "Space per transport", "Fuel/sector"],
            cargo_rows,
        ),
        "",
        "The four things a world can build as fixed defense.",
        "",
        _md_table(
            ["Defense", "Tech", "Power", "Weap eff", "Def adj", "Build rate", "che / met / tri"],
            def_rows,
        ),
        "",
    ]


def _structures() -> list[str]:
    cols = list(CARGO_TYPES)
    rows = []
    for c in CONSTR_TYPES:
        costs = datacnst.ConsCargoNeeded[c]
        rows.append(
            [datacnst.TechnologyName[c], str(datacnst.YearsToBuild[c])]
            + [str(costs[k]) if costs.get(k) else "—" for k in cols]
        )
    return [
        "## Construction",
        "",
        "Years to complete, and the cargo (megatons; ambrosia and trillum",
        "kilotons) a site consumes **per year** while under construction.",
        "",
        _md_table(
            ["Structure", "Years"] + [datacnst.TechnologyName[k] for k in cols],
            rows,
        ),
        "",
    ]


def _raw_material_costs() -> list[str]:
    cols = RAWM_TYPES
    rows = []
    order = [
        T.amb,
        T.fgt,
        T.hkr,
        T.jmp,
        T.jtn,
        T.pen,
        T.ssp,
        T.trn,
        T.men,
        T.nnj,
        T.LAM,
        T.def_,
        T.GDM,
        T.ion,
        T.SRM,
    ]
    for thing in order:
        if thing not in datacnst.RawM:
            continue
        costs = datacnst.RawM[thing]
        rows.append([datacnst.TechnologyName[thing]] + [str(costs.get(c, "—")) for c in cols])
    return [
        "## Raw-Material Costs",
        "",
        "Raw materials consumed to build 100 units of each thing. (Structures",
        "are built by year and are in the construction table instead; their",
        "per-year rate scales the same way.)",
        "",
        _md_wide_table(["Thing"] + [_short_head(c) for c in cols], rows, label_w=13),
        "",
    ]


def _combat() -> list[str]:
    attackers = list(attack.ATTACK_TYPES)
    header = ["Attacker \\ defender"] + [_short_name(d) for d in attackers]
    rows = []
    for at in attackers:
        row = [datacnst.TechnologyName[at] or "—"]
        for d in attackers:
            row.append(str(datacnst.CombatTable[at][d]))
        rows.append(row)
    tech_rows = []
    for a in TechLevel:
        tech_rows.append(
            [_level_row(a)] + [str(attack.CombatTechAdj[a][d]) for d in TechLevel]
        )
    gdm_rows = [
        [datacnst.TechnologyName[s], str(attack.GDMKill[s])] for s in SHIP_TYPES
    ]
    power_rows = [
        [datacnst.TechnologyName[t], str(attack.CombatPower[t])]
        for t in attack.ATTACK_TYPES
        if attack.CombatPower[t]
    ]
    return [
        "## Combat",
        "",
        "### The combat table",
        "",
        "Destructive power of attacker against defender. At the standard",
        "adjustments, 100 points of accumulated damage destroys one unit,",
        "200 destroys two, and so on.",
        "",
        _md_wide_table(header, rows),
        "",
        "### Military power (surrender test)",
        "",
        "Powers used when weighing whether a beaten world surrenders.",
        "",
        _md_table(["Weapon", "Power"], power_rows),
        "",
        "### Technology adjustment",
        "",
        "Percent applied to the attacker's power for attacker technology",
        "(rows) against defender technology (columns). 100 is no",
        "adjustment.",
        "",
        _md_table(["Attacker \\ defender"] + [_level_row(d) for d in TechLevel], tech_rows),
        "",
        "### GDM interception",
        "",
        "Ground-defense missiles shot down on approach per 10 attacking",
        "ships of the type.",
        "",
        _md_table(["Ship", "GDMs killed"], gdm_rows),
        "",
    ]


def _world_classes() -> list[str]:
    rows = []
    for wc in WorldClass:
        ind = datacnst.ClassIndAdj[wc]
        rows.append(
            [
                ClassN[wc],
                datacnst.ClassStr[wc],
                _level_row(datacnst.MinTechForClass[wc]),
                str(datacnst.TriResByClass[wc]),
                str(attack.CombatClassAdj[wc]),
            ]
            + [str(ind[i]) for i in IndusTypes]
        )
    return [
        "## World Classes",
        "",
        "The world's class sets its trillum reserve, how strongly its terrain",
        "aids ground defense, and the percent of each industry that is",
        "effective on it. Industry column heads: Bio (labs), Che (micals),",
        "Min (es), SYG / SYJ / SYS / SYT (the four ship yards), Sup (plies),",
        "Tri (llium).",
        "",
        _md_wide_table(
            ["Class", "Glyph", "Min tech", "Tri res.", "Gd def."]
            + [_short_head(i) for i in IndusTypes],
            rows,
            label_w=13,
        ),
        "",
    ]


def _world_types() -> list[str]:
    rows = []
    for wt in WorldTypes:
        rows.append(
            [
                datacnst.TypeName[wt],
                datacnst.TypeStr[wt],
                _level_row(datacnst.MinTechForType[wt]),
                datacnst.IndusNames[datacnst.PrincipalIndustry[wt]],
                str(datacnst.OptMilitary[wt]),
            ]
        )
    return [
        "## World Designations",
        "",
        "The technology needed before a world may be designated, its",
        "principal industry, and the optimum military index for that",
        "designation (hundredths of a percent of population in uniform).",
        "",
        _md_table(
            ["Designation", "Glyph", "Min tech", "Principal industry", "Opt military"],
            rows,
        ),
        "",
    ]


def _fleets_and_limits() -> list[str]:
    fleet_rows = [
        [
            {
                FleetTypes.Standard: "Standard fleet",
                FleetTypes.JumpFleet: "Jump fleet",
                FleetTypes.HKFleet: "Hunter-killer force",
                FleetTypes.Penetrator: "Penetrator force",
                FleetTypes.AdvWrpFleet: "Advanced-warp fleet",
            }[ft],
            str(rate),
        ]
        for ft, rate in datacnst.FltMovementRate.items()
    ]
    limit_rows = [
        ("Worlds", str(types.MAX_NO_OF_PLANETS)),
        ("Starbases", str(types.MAX_NO_OF_STARBASES)),
        ("Fleets, total", str(types.MAX_NO_OF_FLEETS)),
        ("Fleets per empire", str(types.NO_OF_FLEETS_PER_EMPIRE)),
        ("Stargates", str(types.MAX_NO_OF_STARGATES)),
        ("Construction sites", str(types.MAX_NO_OF_CONSTR_SITES)),
        ("Probe packets per empire", str(types.NO_OF_PROBES_PER_EMPIRE)),
        ("Names per empire", str(types.NO_OF_NAMES_PER_EMPIRE)),
        ("Groups per attack", str(attack.MAX_NO_OF_GROUPS)),
        ("Max resources", str(types.MAX_RESOURCES)),
    ]
    return [
        "## Fleets and Movement",
        "",
        "Fleet movement rate in sectors per year, by fleet type. A fleet's",
        "type is the slowest ship it contains.",
        "",
        _md_table(["Fleet type", "Sectors / year"], fleet_rows),
        "",
        "Other movement and cargo constants:",
        "",
        f"- Jump and jump-transport bases project a fleet of up to "
        f"**{datacnst.JUMP_CARGO_RATIO} transports** worth of cargo "
        f"(or the ship-count equivalent).",
        f"- Fuel per ton of cargo: **{datacnst.FUEL_PER_TON}** (thousandths).",
        f"- A standing fleet in space burns its type's fuel consumption "
        f"divided by **{datacnst.SFUEL_CONS}** per turn.",
        "- Warp distance is Chebyshev: a diagonal sector costs the same as",
        "  an orthogonal one.",
        "",
        "## Game Limits",
        "",
        _md_table(["Thing", "Maximum"], limit_rows),
        "",
    ]


# --- versions and metadata -----------------------------------------------------


def version() -> str:
    with (REPO / "pyproject.toml").open("rb") as f:
        return tomllib.load(f)["project"]["version"]


def build_date() -> str:
    import os

    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch is not None:
        return datetime.fromtimestamp(int(epoch), tz=timezone.utc).strftime("%Y-%m-%d")
    return datetime.now().strftime("%Y-%m-%d")


def chapter_files() -> list[Path]:
    return sorted(CHAPTERS_DIR.glob("*.md"))


# --- pandoc ---------------------------------------------------------------------


def _pandoc(args: list[str]) -> None:
    exe = shutil.which("pandoc")
    if exe is None:
        sys.exit("pandoc not found on PATH; install it (and typst) to build the manual")
    subprocess.run([exe, *args], check=True, cwd=HERE)


def build_pdf() -> None:
    _pandoc(
        [
            *[str(p.relative_to(HERE)) for p in chapter_files()],
            str(APPENDIX_PATH.relative_to(HERE)),
            "-o",
            str(PDF_PATH.name),
            "--pdf-engine=typst",
            "--template=template.typ",
            "--toc",
            "--toc-depth=2",
            "-M",
            "title=Player's Manual",
            "-M",
            f"version={version()}",
            "-M",
            f"date={build_date()}",
            "-M",
            "emblem=logo.svg",
        ]
    )


def build_html() -> None:
    _pandoc(
        [
            *[str(p.relative_to(HERE)) for p in chapter_files()],
            str(APPENDIX_PATH.relative_to(HERE)),
            "-o",
            str(HTML_PATH.name),
            "--standalone",
            "--embed-resources",
            "--toc",
            "--toc-depth=2",
            "--css=manual.css",
            "-M",
            "lang=en",
            "-M",
            "title=Re:creon Player's Manual",
            "-M",
            "subtitle=Anacreon: Reconstruction 4021",
            "-M",
            "author=The Re:creon project",
            "-M",
            f"version={version()}",
            "-M",
            f"date={build_date()}",
        ]
    )


# --- appendix write/check ----------------------------------------------------------


def write_appendix() -> bool:
    """Returns True if the file changed (or was created)."""
    text = appendix()
    if APPENDIX_PATH.exists() and APPENDIX_PATH.read_text() == text:
        return False
    APPENDIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    APPENDIX_PATH.write_text(text)
    return True


def check_appendix() -> bool:
    """True when the committed appendix matches what the game data says."""
    return APPENDIX_PATH.exists() and APPENDIX_PATH.read_text() == appendix()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tables", action="store_true", help="regenerate the appendix and exit")
    parser.add_argument("--check", action="store_true", help="verify the appendix and exit")
    args = parser.parse_args(argv)

    if args.check:
        if not check_appendix():
            print("appendix-reference.md is stale; run build.py --tables", file=sys.stderr)
            return 1
        return 0

    changed = write_appendix()
    if changed:
        print(f"regenerated {APPENDIX_PATH.relative_to(REPO)}")
    if args.tables:
        return 0

    build_pdf()
    build_html()
    print(f"wrote {PDF_PATH.relative_to(REPO)} and {HTML_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
